package com.mkobit.jenkins.pipelines

import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.process.CommandLineArgumentProvider

/**
 * Emits `test.library.N.{name,location,implicit}` JVM system properties for each peer Jenkins
 * shared library on a test task. Indices start at `1` — index `0` is reserved for the project's
 * own (self-)library injected by [LibraryNameArgumentProvider] and [LibraryLocationArgumentProvider].
 *
 * The auto-registrar generated by [GenerateLocalLibraryFiles] iterates contiguous indices at
 * Jenkins startup; this provider supplies indices `1, 2, …` in declaration order.
 *
 * Inputs are split:
 *  - [entries] carries the structured data (name, location path, implicit flag) and is treated
 *    as a regular `@Input` (serialized via Java for configuration-cache compatibility).
 *  - [sourceDirectories] carries the resolved source directories purely for Gradle's
 *    path-sensitive up-to-date checking; the location paths inside [entries] are what
 *    actually feed `asArguments`.
 */
abstract class PeerLibrariesArgumentProvider : CommandLineArgumentProvider {
  @get:Input
  abstract val entries: ListProperty<PeerLibraryEntry>

  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  override fun asArguments(): List<String> =
    entries.get().flatMapIndexed { idx, entry ->
      val i = idx + 1
      listOf(
        "-Dtest.library.$i.name=${entry.libraryName}",
        "-Dtest.library.$i.location=${entry.locationPath}",
        "-Dtest.library.$i.implicit=${entry.implicit}",
      )
    }
}
