package com.mkobit.jenkins.pipelines

import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.process.CommandLineArgumentProvider

/**
 * Emits `test.library.N.{name,location,implicit}` JVM system properties for every Jenkins shared
 * library on a test task. [entries] is ordered: the consumer's own library at index 0, followed
 * by peer libraries at indices 1, 2, … in declaration order. The auto-registrar generated by
 * [GenerateLocalLibraryFiles] iterates contiguous indices at Jenkins startup, so this ordering
 * is part of the contract.
 *
 * Inputs are split:
 *  - [entries] carries the structured data (name, location path, implicit flag) and is treated
 *    as a regular `@Input` (serialized via Java for configuration-cache compatibility).
 *  - [sourceDirectories] carries the resolved source directories purely for Gradle's
 *    path-sensitive up-to-date checking; the location paths inside [entries] are what
 *    actually feed `asArguments`.
 */
abstract class SharedLibrariesArgumentProvider : CommandLineArgumentProvider {
  @get:Input
  abstract val entries: ListProperty<SharedLibraryEntry>

  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  override fun asArguments(): List<String> {
    val allEntries = entries.get()
    val duplicates =
      allEntries
        .groupingBy { it.libraryName }
        .eachCount()
        .filterValues { it > 1 }
        .keys
    if (duplicates.isNotEmpty()) {
      throw GradleException(
        "duplicate Jenkins shared library name(s): ${duplicates.joinToString(", ")}. " +
          "Each library registered in Jenkins must have a unique name; set a distinct " +
          "`libraryName` on the colliding entry in the sharedLibrary { dependencies { } } block.",
      )
    }
    return allEntries.flatMapIndexed { idx, entry ->
      listOf(
        "-Dtest.library.$idx.name=${entry.libraryName}",
        "-Dtest.library.$idx.location=${entry.locationPath}",
        "-Dtest.library.$idx.implicit=${entry.implicit}",
      )
    }
  }
}
