package com.mkobit.jenkins.pipelines

import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.process.CommandLineArgumentProvider

/**
 * Emits `test.library.N.{name,location,implicit}` JVM system properties for every Jenkins shared
 * library on a test task — the consumer's own library at index 0, followed by [peerEntries] at
 * indices 1, 2, … in declaration order.
 *
 * The auto-registrar generated by [GenerateLocalLibraryFiles] iterates contiguous indices at
 * Jenkins startup; entries must therefore be ordered (self first, then peers).
 *
 * Inputs are split:
 *  - Self-library metadata ([selfLibraryName], [selfLibraryLocation], [selfLibraryImplicit]) and
 *    [peerEntries] carry the structured data and are treated as `@Input`/`@InputDirectory`
 *    (serialized via Java for configuration-cache compatibility).
 *  - [sourceDirectories] carries the resolved source directories purely for Gradle's
 *    path-sensitive up-to-date checking.
 */
internal abstract class SharedLibrariesArgumentProvider : CommandLineArgumentProvider {
  @get:Internal
  abstract val selfLibraryName: Property<String>

  @get:InputDirectory
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val selfLibraryLocation: DirectoryProperty

  @get:Internal
  abstract val selfLibraryImplicit: Property<Boolean>

  @get:Input
  abstract val peerEntries: ListProperty<SharedLibraryEntry>

  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  override fun asArguments(): List<String> {
    val allEntries =
      listOf(
        SharedLibraryEntry(
          libraryName = selfLibraryName.get(),
          locationPath = selfLibraryLocation.get().asFile.absolutePath,
          implicit = selfLibraryImplicit.get(),
        ),
      ) + peerEntries.get()
    val duplicates =
      allEntries
        .groupingBy { it.libraryName }
        .eachCount()
        .filterValues { it > 1 }
        .keys
    if (duplicates.isNotEmpty()) {
      throw GradleException(
        "duplicate Jenkins shared library name(s): ${duplicates.joinToString(", ")}. " +
          "Each library registered in Jenkins must have a unique name; set a distinct " +
          "`libraryName` on the colliding entry in the sharedLibrary { dependencies { } } block.",
      )
    }
    return allEntries.flatMapIndexed { idx, entry ->
      listOf(
        "-Dtest.library.$idx.name=${entry.libraryName}",
        "-Dtest.library.$idx.location=${entry.locationPath}",
        "-Dtest.library.$idx.implicit=${entry.implicit}",
      )
    }
  }
}
