changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
