= Changelog
:toc:
:toclevels: 2
:uri-keep-a-changelog: http://keepachangelog.com/en/1.0.0/
:uri-semver: http://semver.org/spec/v2.0.0.html

This document is based on thelink:{uri-keep-a-changelog}[Keep a Changelog 1.0.0 specification].

This project follows link:{uri-semver}[the semantic version 2.0 specification].

Each new should include:

* Version (semantic version)
* Date of release (in `yyyy/mm/dd` format)

For each release, a subsection should be added for each of the following if they are non-empty:

* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

== UNRELEASED (yyyy/mm/dd)

Built and tested on Gradle 4.3.

=== Added

* Generated classes for integration tests in the `com.mkobit.jenkins.pipelines.codegen` package namespace.
  The first generated class is the `LocalLibraryRetriever` which can be used as a `LibraryRetriever` for fast feedback in integration tests.
  See the integration tests or example library for how to use the generated classes.

=== Changed

* `integrationTest` will executed after `test` if they are both included in the build
* `check` now `dependsOn` `integrationTest`
* Default Jenkins Test Harness version: `2.28` to `2.31`
* Default Jenkins Core Version version: `2.73.1` to `2.73.2`

=== Removed

* The helper methods from `PluginDependencySpec` for adding dependencies from different groups.
  `cloudbees()`, `workflow()`, `jvnet()`, `jenkinsCi()`, and `blueocean()` have all been removed.

== 0.2.0 (2017/10/04)

Fixes publishing issues with first release

== 0.1.0 (2017/09/11)

Initial release
