= Changelog
:toc:
:toclevels: 2
:uri-keep-a-changelog: http://keepachangelog.com/en/1.0.0/
:uri-semver: http://semver.org/spec/v2.0.0.html

This document is based on thelink:{uri-keep-a-changelog}[Keep a Changelog 1.0.0 specification].

This project follows link:{uri-semver}[the semantic version 2.0 specification].

Each new should include:

* Version (semantic version)
* Date of release (in `yyyy/mm/dd` format)

For each release, a subsection should be added for each of the following if they are non-empty:

* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

== UNRELEASED

=== Changed

* Upgraded to Gradle 4.4.1
* Upgraded to Kotlin 1.2.10
* Updated default versions:
+
[cols="3*",options="header"]
|===
|Component
|From
|TO

|Core
|2.73.2
|2.89,2

|Test Harness
|2.31
|2.33

|Workflow API Plugin
|2.22
|2.24

|Workflow CPS Plugin
|2.40
|2.42

|Workflow Durable Task Step Plugin
|2.15
|2.17

|Workflow Job Plugin
|2.14.1
|2.16

|Workflow Step API Plugin
|2.13
|2.14

|Workflow Support Plugin
|2.15
|2.16
|===

=== Fixed

* Generated library retriever First step from pipeline execution no longer not log on same line as generated library retriever

== 0.3.2 (2017/10/31)

=== Fixed

* Constructor visibility in generated library retriever should be `public`

== 0.3.1 (2017/10/31)

=== Fixed

* Build fails when ran in a non-clean workspace

== 0.3.0 (2017/10/31)

Built and tested on Gradle 4.3.

=== Added

* Generated classes for integration tests in the `com.mkobit.jenkins.pipelines.codegen` package namespace.
  The first generated class is the `LocalLibraryRetriever` which can be used as a `LibraryRetriever` for fast feedback in integration tests.
  See the integration tests or example library for how to use the generated classes.

=== Changed

* `integrationTest` will executed after `test` if they are both included in the build
* `check` now `dependsOn` `integrationTest`
* Default Jenkins Test Harness version: `2.28` to `2.31`
* Default Jenkins Core Version version: `2.73.1` to `2.73.2`

=== Removed

* The helper methods from `PluginDependencySpec` for adding dependencies from different groups.
  `cloudbees()`, `workflow()`, `jvnet()`, `jenkinsCi()`, and `blueocean()` have all been removed.
* `git-plugin` no longer included

== 0.2.0 (2017/10/04)

Fixes publishing issues with first release

== 0.1.0 (2017/09/11)

Initial release
