= Changelog
:toc:
:toclevels: 2
:uri-keep-a-changelog: http://keepachangelog.com/en/1.0.0/
:uri-semver: http://semver.org/spec/v2.0.0.html

This document is based on thelink:{uri-keep-a-changelog}[Keep a Changelog 1.0.0 specification].

This project follows link:{uri-semver}[the semantic version 2.0 specification].

Each new should include:

* Version (semantic version)
* Date of release (in `yyyy/mm/dd` format)

For each release, a subsection should be added for each of the following if they are non-empty:

* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

== 0.6.1 (2018/04/11)

=== Fixed

* Error logs and problems with JEP-200 with latest Jenkins 2.107.1 LTS release (see these blog posts - link:https://jenkins.io/blog/2018/01/13/jep-200/[2018/01/13/jep-200], link:https://jenkins.io/blog/2018/03/15/jep-200-lts[2018/03/15/jep-200-lts])

== 0.6.0 (2018/04/10)

=== Added

* All `org.jenkins-ci.modules` group dependencies from the `jenkins-war` dependency are included in integration tests.
  This should hopefully reduce a lot of the standard out error noise by Jenkins during tests.

=== Changed

* `javapoet`, `okhttp`, and `kotlin-logging` package version upgrades
* *Breaking* - all exposed extension properties have been changed to the link:https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html[`Property`] API.
  In Groovy, the existing DSL still works fine due to Gradle DSL decoration:
+
[source, groovy]
----
sharedLibrary {
  coreVersion = "2.114"
  testHarnessVersion = "2.32"
  pluginDependencies {
    workflowCpsPluginVersion = "2.4"
    workflowCpsGlobalLibraryPluginVersion = "2.9"
    dependency("io.jenkins.blueocean", "blueocean-web", "1.3.0")
  }
}
----
However if using the Kotlin DSL, you will need to use `.set` until link:https://github.com/gradle/kotlin-dsl/issues/380[kotlin-dsl/380] is resolved.
+
[source, kotlin]
----
sharedLibrary {
  coreVersion.set("2.86")
  testHarnessVersion.set("2.32")
  pluginDependencies {
    workflowCpsGlobalLibraryPluginVersion.set("2.9")
    workflowCpsPluginVersion.set("2.4")
    dependency("io.jenkins.blueocean", "blueocean-web", "1.3.0")
  }
}
----

=== Changed

* Updated default versions:
+
[cols="3*",options="header"]
|===
|Component
|From
|TO

|Core
|2.89.4
|2.107.1

|Test Harness
|2.34
|2.38

|Workflow CPS Plugin
|2.45
|2.47

|Workflow Job Plugin
|2.17
|2.18

|===

== 0.5.0 (2018/03/06)

=== Added

* New plugin to integrate with a specific Jenkins instance.
  This will be built upon in the future to allow for auto-management of dependencies.
  For now, a few tasks are added to download the GDSL, retrieve the plugin lists if you have appropriate permissions, and retrieve the core version.
  These tasks are experimental until better support arrives.
+
[source, groovy]
----
import java.net.URL
import com.mkobit.jenkins.pipelines.http.BasicAuthentication

jenkinsIntegration {
  baseUrl = new URL('https://mycorp.jenkins.zone')
  authentication = providers.provider { new BasicAuthentication(property('username'), property('password') }
}
----
+
[source]
----
./gradlew retrieveJenkinsGdsl
./gradlew retrieveJenkinsPluginData
./gradlew retrieveJenkinsVersion
----
* Support for using Jenkins core and plugins in library source code
* Support for `@Grab` in library source
+
WARNING: Unit testing code that uses `@Grab` does not seem to work.
         See link:https://stackoverflow.com/questions/4611230/no-suitable-classloader-found-for-grab[this StackOverflow question].
         You can, however, still test other code that does not use `@Grab`

=== Changed

* Updated default versions:
+
[cols="3*",options="header"]
|===
|Component
|From
|TO

|Core
|2.89.2
|2.89.4

|Test Harness
|2.33
|2.34

|Workflow API Plugin
|2.24
|2.26

|Workflow CPS Plugin
|2.42
|2.45

|Workflow Durable Task Step Plugin
|2.17
|2.19

|Workflow Job Plugin
|2.16
|2.17

|Workflow Support Plugin
|2.16
|2.18
|===

=== Fixed

* KDoc links to external documentation

=== Removed

* Support for Gradle 4.3, 4.4, and 4.5.
  Only 4.6 is supported right now.
* `integrationTest` source set configurations no longer extends from any `test` source set configurations.
  You will now need to specify dependencies for both.

== 0.4.0 (2018/01/06)

=== Added

* Support for `@NonCPS` in library definition

=== Changed

* Upgraded to Gradle 4.4.1
* Upgraded to Kotlin 1.2.10
* Updated default versions:
+
[cols="3*",options="header"]
|===
|Component
|From
|TO

|Core
|2.73.2
|2.89.2

|Test Harness
|2.31
|2.33

|Workflow API Plugin
|2.22
|2.24

|Workflow CPS Plugin
|2.40
|2.42

|Workflow Durable Task Step Plugin
|2.15
|2.17

|Workflow Job Plugin
|2.14.1
|2.16

|Workflow Step API Plugin
|2.13
|2.14

|Workflow Support Plugin
|2.15
|2.16
|===

=== Fixed

* Generated library retriever no longer logs on the same line as the first step

== 0.3.2 (2017/10/31)

=== Fixed

* Constructor visibility in generated library retriever should be `public`

== 0.3.1 (2017/10/31)

=== Fixed

* Build fails when ran in a non-clean workspace

== 0.3.0 (2017/10/31)

Built and tested on Gradle 4.3.

=== Added

* Generated classes for integration tests in the `com.mkobit.jenkins.pipelines.codegen` package namespace.
  The first generated class is the `LocalLibraryRetriever` which can be used as a `LibraryRetriever` for fast feedback in integration tests.
  See the integration tests or example library for how to use the generated classes.

=== Changed

* `integrationTest` will executed after `test` if they are both included in the build
* `check` now `dependsOn` `integrationTest`
* Default Jenkins Test Harness version: `2.28` to `2.31`
* Default Jenkins Core Version version: `2.73.1` to `2.73.2`

=== Removed

* The helper methods from `PluginDependencySpec` for adding dependencies from different groups.
  `cloudbees()`, `workflow()`, `jvnet()`, `jenkinsCi()`, and `blueocean()` have all been removed.
* `git-plugin` no longer included

== 0.2.0 (2017/10/04)

Fixes publishing issues with first release

== 0.1.0 (2017/09/11)

Initial release
