/**
 * Jenkins Script Console — export installed plugins as a Gradle version catalog.
 *
 * Run this in Manage Jenkins → Script Console on the Jenkins instance whose plugin
 * versions you want to pin in your shared library's test dependencies.
 *
 * The output is a valid `jenkins.versions.toml` file.  Save it to
 * `gradle/jenkins.versions.toml` in your shared library project and wire it in
 * `settings.gradle.kts`:
 *
 *   dependencyResolutionManagement {
 *     versionCatalogs {
 *       create("jenkinsLibs") {
 *         from(files("gradle/jenkins.versions.toml"))
 *       }
 *     }
 *   }
 *
 * Then reference plugins by their short name as typed accessors:
 *
 *   jenkinsPlugin(jenkinsLibs.workflow.job)
 *   jenkinsPlugin(jenkinsLibs.pipeline.model.definition)
 *
 * Re-run and replace the file whenever plugins are upgraded on the instance.
 */

import hudson.PluginWrapper

// Convert a plugin short name (kebab-case) to a TOML key (dots for nesting, safe characters).
// "workflow-job" → "workflow.job", "pipeline-model-api" → "pipeline.model.api"
def tomlKey(String shortName) {
  shortName.replaceAll('-', '.')
}

def plugins = Jenkins.instance.pluginManager.plugins
  .findAll { PluginWrapper p -> p.isActive() && !p.isDeleted() }
  .collect { PluginWrapper p ->
    def groupId = p.manifest.mainAttributes.getValue('Group-Id') ?: 'unknown'
    [groupId: groupId, shortName: p.shortName, version: p.version, displayName: p.displayName]
  }
  .sort { it.shortName }

def sb = new StringBuilder()

sb << "# Generated by scripts/export-jenkins-catalog.groovy\n"
sb << "# Source: ${Jenkins.instance.rootUrl ?: 'unknown'}\n"
sb << "# Jenkins: ${Jenkins.VERSION}\n"
sb << "# Date: ${new Date()}\n\n"

sb << "[versions]\n"
plugins.each { p ->
  sb << "${tomlKey(p.shortName)} = \"${p.version}\"\n"
}

sb << "\n[libraries]\n"
plugins.each { p ->
  if (p.groupId == 'unknown') {
    sb << "# WARNING: no Group-Id in manifest for ${p.shortName} — add group manually\n"
    sb << "# ${tomlKey(p.shortName)} = { module = \"?:${p.shortName}\", version.ref = \"${tomlKey(p.shortName)}\" }\n"
  } else {
    sb << "${tomlKey(p.shortName)} = { module = \"${p.groupId}:${p.shortName}\", version.ref = \"${tomlKey(p.shortName)}\" }\n"
  }
}

print sb.toString()
