name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and deploy Dokka HTML
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: '17'
          distribution: temurin
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
        with:
          gradle-version: "9.4.1"
      - name: Generate Dokka HTML
        run: gradle dokkaGeneratePublicationHtml
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: build/dokka/html
      - id: deploy
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
