name: Validate Gradle wrapper

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
